version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: cimg/node:16.13
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: build
          command: yarn build
      - run:
          name: create dir
          command: mkdir ~/project/artifacts
      - run:
          name: move files
          command: |
            cp package-prd.json ~/project/artifacts/package.json
            mv index.js ~/project/artifacts/index.js
      - store_artifacts:
          path: ~/project/artifacts

workflows:
  main:
    jobs:
      - node/run:
          version: "16.13"
          pkg-manager: yarn
          yarn-run: lint
      - build:
          requires:
            - "node/run"
