version: 2.1

orbs:
  node: circleci/node@4.7
  slack: circleci/slack@4.4.2
  jq: circleci/jq@2.2.0

jobs:
  build:
    docker:
      - image: cimg/node:16.13
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: build
          command: yarn build
      - run:
          name: create dir
          command: mkdir ~/project/artifacts
      - run:
          name: move files
          command: |
            cp package-prd.json ~/project/artifacts/package.json
            mv index.js ~/project/artifacts/index.js
      - store_artifacts:
          path: ~/project/artifacts
      - jq/install
      - run:
          name: Get artifacts
          command: |
            artifacts=$(curl -X GET "https://circleci.com/api/v2/project/github/YutaGoto/hyper-tsumugu/$CIRCLE_BUILD_NUM/artifacts" \
            -H "Accept: application/json" \
            --header "Circle-Token: $CIRCLE_TOKEN")
            echo $artifacts
            artifact0=$(echo $artifacts | jq '.items[0].url')
            artifact1=$(echo $artifacts | jq '.items[1].url')
            echo "export ARTIFACT0=$artifact0" >> $BASH_ENV 
            echo "export ARTIFACT1=$artifact1" >> $BASH_ENV
      - run:
          command: echo "${ARTIFACT1}"
      - slack/notify:
          event: always
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Hyper-Tsumugu Artifacts index.js"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "index.js",
                      "emoji": true
                    },
                    "value": "click0",
                    "url": "${ARTIFACT0}",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Hyper-Tsumugu Artifacts package.json"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "package.json",
                      "emoji": true
                    },
                    "value": "click1",
                    "url": "${ARTIFACT1}",
                    "action_id": "button-action"
                  }
                }
              ]
            }


workflows:
  main:
    jobs:
      - node/run:
          version: "16.13"
          pkg-manager: yarn
          yarn-run: lint
      - build:
          requires:
            - "node/run"
          context:
            - slack
